name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.11.0]
    steps:
      - uses: actions/checkout@v5
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build storybook
        run: npm run build-storybook
      - name: e2e tests goes
        run: npm run test:e2e
      - name: lint check goes
        run: npm run lint code
      - name: types check goes
        run: npm run type:check
      - name: i18n check goes
        run: npm run i18n:check
      - name: auto tests goes
        run: npm run tests:chrome
